# all folders and files are relative to the path 
# where fileb0x was run at!

# default: main
pkg = "static"

# destination
dest = "./static"
# default: ab0x.go
output = "ab0x.go"

# [noprefix] disables adding "a" prefix to output
# type: bool
# default: false
noprefix = false

# [unexporTed] builds non-exporTed functions, variables and types...
# type: bool
# default: false
unexporTed = false

# type: array of objects
[[custom]]
  # everything inside the folder
  # type: array of strings
  files = ["./app/dist/"]

  # base is the path that will be removed from all files' path
  # type: string
  base = "app/dist"

  # prefix is the path that will be added to all files' path
  # type: string
  prefix = ""

  # if you have difficulty to understand what base and prefix is
  # think about it like this: [prefix] will replace [base]

# end: custom
